name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  runCodeQualityChecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install Prettier & ESLint
        run: npm install prettier eslint

      - name: Format code using Prettier
        run: npm run format

      - name: Lint source code
        run: npm run lint

  # TODO: Run test suite

  runNextBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          
      - name: Install dependencies for Next.js Build
        run: npm install
        
      - name: Run Next.js build to generate the static files
        run: npm run build

  # Deploy to Netlify
  deploy:
    needs: runNextBuild
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
<<<<<<< HEAD
          args: deploy --dir=../../.next --prod
=======
          args: deploy --dir=.next --prod
>>>>>>> cb4e267748eb8d8c0a2c5543d28919b9b0c3fff4
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
        # timeout-minutes: 1

  # TODO: Health check job
