name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  runCodeQualityChecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          # cache: "npm"

      - name: Install Prettier & ESLint
        run: npm install prettier eslint

      - name: Format code using Prettier
        run: npm run format

      - name: Lint source code
        run: npm run lint

  # TODO: Run test suite

  runNextBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          # cache: "npm"
          
      - name: 🧰 Install dependencies for Next.js Build
        run: npm install
        
      - name: 📦 Run Next.js build to generate the static files
        run: npm run build
  
  deploy:
    runs-on: ubuntu-latest
    needs: runNextBuild
    steps:
      # - name: Install Netlify CLI
      #   run: npm install netlify-cli --save-dev

      
      # - name: Build Project
      #   run: npm netlify build

      # - name: Deploy
      #   run: netlify deploy
      - name: Build Project
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}


      - name: Deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=.next --functions=functions
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  # TODO: Health check job
