name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  runCodeQualityChecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependecies
        run: npm ci

      - name: Format code using Prettier
        run: npm run format

      - name: Lint source code
        run: npm run lint

  # TODO: Run test suite

  runNextBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies for Next.js Build
        run: npm ci

      - name: Run Next.js build to generate the static files
        run: npm run build

        # Runs the deploy command
        # Parses the output, and 
        # retrieves the build log url & the deployed url,
        # finally stores them into variables: NETLIFY_LOGS_URL & NETLIFY_LIVE_URL
      - name: 🚀Deploy
        id: deploy-netlify
        run: |
          COMMAND="netlify deploy --build --prod"
          OUTPUT=$(sh -c "$COMMAND")

          NETLIFY_LOGS_URL=$(echo "$OUTPUT" \
          | grep -Eo '(http|https)://app.netlify.com/[a-zA-Z0-9./?=_-]*')
          # Unique key: app.netlify.com
          
          NETLIFY_LIVE_URL=$(echo "$OUTPUT" \
          | grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*' | grep -Ev "netlify.com|(--)")
          # Unique key: doesn't contain -- and app.netlify.com

          echo "::set-output name=netlify_logs_url::$NETLIFY_LOGS_URL"
          echo "::set-output name=netlify_live_url::$NETLIFY_LIVE_URL"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

       # Takes the Logs url and live url from previous job
       # and creates a comment on commit
      - name: 👓 Netlify Preview URL
        uses: peter-evans/commit-comment@v1
        env:
            OUTPUT: |
              ### Successfully deployed to Netlify.

              🔍 Inspect: ${{ steps.deploy-netlify.outputs.NETLIFY_LOGS_URL }}
              ✅ Preview: ${{ steps.deploy-netlify.outputs.NETLIFY_LIVE_URL }}
        with:
          body: ${{ env.OUTPUT }}
